database:
  url: postgres://postgres@localhost:5432/utm_postback_middle_dev
  ConnMaxLifetime: 5
  MaxOpenConns: 1

server:
  ListenAddr: ':3000'
  AuthToken: '81bddcd4-1a93-4a4b-a56f-3677487f89e2'
  Host: 'http://localhost:3000'

appsflyer:
  Url: https://api2.appsflyer.com/inappevent/
  ApiKey: zX9ThYKiH9eLaWhr6jEv8o

kafka:
  Brokers: ['localhost:9092']
  Topics: ['vn', 'my', 'ph', 'id', 'lk']