// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"fmt"
	"github.com/swaggo/swag"
	"io/ioutil"
)

var doc = `{
    "swagger": "2.0",
    "info": {
        "description": "This is a postback server and creating event server for appsflyer",
        "title": "ERROR %s",
        "contact": {
            "name": "API Support",
            "email": "maxim.aleynikov@cashwagon.com"
        }
    }
}
`

type s struct{}

func (s *s) ReadDoc() string {
	data, err := ioutil.ReadFile("./docs/openapi.json")
	if err != nil {
		return fmt.Sprintf(doc, err)
	}
	return string(data)
}

func init() {
	swag.Register(swag.Name, &s{})
}
